In [2]:
import pandas as pd
import numpy as np

In [3]:
test_file = pd.read_csv('test.csv')

test_file.sample(5)

,case_id,modality,body_part,study_description,patient_age_band,patient_sex,template_content,dictation
9,0c89b0eb-2ad2-4f31-8f80-f2bb4cd8679a,MRI,Abdomen,MRI Abdomen,60-64,female,FINDINGS:\nLOWER THORAX: No pleural effusion o...,"Gallbladder is not visualized, consistent with..."
105,89cb3fe2-9aee-4e4a-85c3-e0e5a099b911,MRI,Thoracic spine,MRI T-SPINE WO,75-79,female,"FINDINGS:\nVERTEBRAE: No acute fracture, sublu...",There is pronounced multilevel thoracic spondy...
40,32566854-3c67-4590-8efc-cf69110fba49,XRAY,Lumbar spine,XRAY LUMBAR,50-54,female,FINDINGS:\nVERTEBRAE: Normal desnity and align...,Mild degenerative spondylotic changes at L5-S1...
126,d14307e6-9059-4dc2-bbd4-6cc58e71f54c,MRI,Abdomen,MRI ABDOMEN / MRCP W & W/O,70-74,female,FINDINGS:\nLIVER: Normal in size and signal. N...,Liver is normal in size and demonstrates homog...
76,5e6776a6-757a-4193-a7ab-8403c63a911d,MRI,Knee,MRI RIGHT KNEE WO,20-24,female,FINDINGS:\nOsseous Structures: No acute fractu...,Menisci mild intrasubstance degenerative signa...

In [6]:
test_file.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   case_id            132 non-null    str
 1   modality           132 non-null    str
 2   body_part          132 non-null    str
 3   study_description  132 non-null    str
 4   patient_age_band   132 non-null    str
 5   patient_sex        132 non-null    str
 6   template_content   132 non-null    str
 7   dictation          132 non-null    str
dtypes: str(8)
memory usage: 8.4 KB

In [ ]:
test_file.isnull

case_id              132
modality             132
body_part            132
study_description    132
patient_age_band     132
patient_sex          132
template_content     132
dictation            132
dtype: int64

In [22]:
#Univariate Analysis

test_file['body_part'].value_counts()  # spotted unknown body parts

body_part
Lumbar spine        17
Knee                16
Shoulder            10
Chest                9
Cervical spine       8
Thoracic spine       7
Hand                 7
Wrist                6
Abdomen              5
Pelvis               5
Brain                5
Hip                  4
Foot                 4
Ankle                4
Head                 4
Forearm bone         2
Arm                  2
Heel                 2
Bladder              1
Liver                1
Orbit                1
Thumb                1
Unknown              1
Ribs                 1
Finger               1
Femur                1
Skull sinus          1
Paranasal sinus      1
Shoulder scapula     1
Neck                 1
Sternum              1
Knee patella         1
Ankle calcaneous     1
Name: count, dtype: int64

In [23]:
test_file.loc[
    test_file['body_part'].eq('Unknown'),
    'case_id'
]

90    759534d0-c00b-4603-8aa6-b67ca3ca8e15
Name: case_id, dtype: str

In [25]:
pd.crosstab(test_file["modality"], test_file["body_part"])

body_part,Abdomen,Ankle,Ankle calcaneous,Arm,Bladder,Brain,Cervical spine,Chest,Femur,Finger,...,Pelvis,Ribs,Shoulder,Shoulder scapula,Skull sinus,Sternum,Thoracic spine,Thumb,Unknown,Wrist
modality,,,,,,,,,,,,,,,,,,,,,
CT,1,0,0,1,0,2,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
MRI,3,2,0,1,0,3,4,0,0,0,...,1,0,4,0,0,0,3,0,0,3
USG,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
XRAY,1,2,1,0,0,0,4,6,1,1,...,3,1,6,1,1,1,4,1,0,3

In [6]:
test_file['patient_age_band'].unique

<bound method Series.unique of 0      60-64
1      40-44
2      50-54
3      50-54
4      65-69
       ...
127    45-49
128    70-74
129    55-59
130    35-39
131    70-74
Name: patient_age_band, Length: 132, dtype: str>